language: node_js
node_js:
- '8'
services: mongodb
env:
  global:
    secure: QTpi+JpVRM1yR+IdPfTiGp6P21FpbLfR5XuPUAB4yQJVZe09AlIYQu8an5LUTxOoEKDwqM8gztbhcw42/1GyL3B/Bt3gO+vtzUIniiV55qdQcGqTuwfnSAN9wpjkUdPcz3omlv6/KDk/hjgBqWiPA5+MmYWvmbCDf1Qx05GxXpkC17RPbP6NF1e7p5G1p51IjVvLtHL6ePoWrWCXUgbPbeWMdQ+N+3ydJKGon0tXNvBQrjSNM7CRdfcuAImHBDpps36s0rqQyNnILm7OQB8fav9O6f0fjn/V2lbBXdagyyqafiznoR6KObhVZcvTfiVlNQCKdlAiu1VI5Njh3/TLV3UQUTgJcZAtXuikFUOuIp1Z5O8QSszaN59Kxxy+CDW8pBIPoWGQfHXnig77XVEM2e7M8gczRmyx/y48IyupBdwYAKG+zvKo0hwOM2Gzc5uw4NXTC79y3HpAFMpv/NbMh2q7TJLUCQJymYDhhtXQTp7V8k0AFug3z+0FtqV8Kkd5+2q2mojIyY3nBNc2kbn7TUvuAPdFVozZuK2Emni6RbUNHIXHKPVPM7j/DrcoA8FzQEaZeUW5Pb6GS2O0InjZUwvU5DemHjLFDNMjD098LLG2XoHN69MVfrgE/TwGOso1WOJXsAJ5o97dL7E7F0gZ5DOexVr3ezsF/KnyDT9fNPs=
